### ISSUE TITLE
HA version 2023.5.0 yields: AttributeError: 'ConfigEntries' object has no attribute 'async_setup_platforms'

### ISSUE THREAD

**Issue by spikeygg** [aijayadams/hass-blueair#19]
Looks like this integration ran into the dreaded:

> Detected integration that called async_setup_platforms instead of awaiting async_forward_entry_setups; this will fail in version 2023.3. Please report issue to the custom integration author for <platform> using this method at <platform file>, line XXX: hass.config_entries.async_setup_platforms(entry, PLATFORMS)

message. :(

Now on HA version 2023.5.0 it fail to start with:

> Traceback (most recent call last):
>   File "/usr/src/homeassistant/homeassistant/config_entries.py", line 387, in async_setup
>     result = await component.async_setup_entry(hass, self)
>   File "/config/custom_components/blueair/__init__.py", line 50, in async_setup_entry
>     hass.config_entries.async_setup_platforms(entry, PLATFORMS)
> AttributeError: 'ConfigEntries' object has no attribute 'async_setup_platforms'

**Comment by chrisdfw** [comment]
Code below is working for me

https://github.com/mmaarrkk02/hass-blueair
