### ISSUE TITLE
error on setup

### ISSUE THREAD

**Issue by unclegueralt** [aijayadams/hass-blueair#21]
hi, i get this issue when i try and set my integration up, nyome know why? Thanks!

This error originated from a custom integration.

Logger: homeassistant.config_entries
Source: custom_components/blueair/__init__.py:50
Integration: BlueAir (documentation, issues)
First occurred: 7:31:00 PM (1 occurrences)
Last logged: 7:31:00 PM

Error setting up entry BlueAir

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 387, in async_setup
    result = await component.async_setup_entry(hass, self)
  File "/config/custom_components/blueair/__init__.py", line 50, in async_setup_entry
    hass.config_entries.async_setup_platforms(entry, PLATFORMS)
AttributeError: 'ConfigEntries' object has no attribute 'async_setup_platforms'

**Comment by TheTravelAddict** [comment]
I also get this error.  It started when I updated HASS to the most recent version (which also caused a Mosquitto error - 
```
Logger: homeassistant.config_entries
Source: custom_components/blueair/__init__.py:50
Integration: BlueAir ([documentation](https://github.com/aijayadams/hass-blueair/), [issues](https://github.com/aijayadams/hass-blueair/issues))
First occurred: 13:23:35 (2 occurrences)
Last logged: 13:32:22

Error setting up entry BlueAir [[my email address]] for blueair
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 387, in async_setup
    result = await component.async_setup_entry(hass, self)
  File "/config/custom_components/blueair/__init__.py", line 50, in async_setup_entry
    hass.config_entries.async_setup_platforms(entry, PLATFORMS)
AttributeError: 'ConfigEntries' object has no attribute 'async_setup_platforms' 
```

**Comment by mmaarrkk02** [comment]
#19

**Comment by TheTravelAddict** [comment]
The following Code below is working for me, but only if I manually overwrite the blueair directory from @mmaarrkk02's project into my custom_components directory.

https://github.com/mmaarrkk02/hass-blueair
