### ISSUE TITLE
Failed to set up  Check the logs

### ISSUE THREAD

**Issue by ychanteloup** [aijayadams/hass-blueair#22]
Integration stopped working after update.

This error originated from a custom integration.

Logger: homeassistant.config_entries
Source: custom_components/Blueair/__init__.py:50 
Integration: Blueair 
First occurred: 16:31:04 (3 occurrences) 
Last logged: 18:11:25

Error setting up entry BlueAir my@email.com for blueair
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 387, in async_setup
    result = await component.async_setup_entry(hass, self)
  File "/config/custom_components/Blueair/__init__.py", line 50, in async_setup_entry
    hass.config_entries.async_setup_platforms(entry, PLATFORMS)
AttributeError: 'ConfigEntries' object has no attribute 'async_setup_platforms'

Home Assistant 2023.5.4
Supervisor 2023.04.1
Operating System 10.1
Frontend 20230503.3 - latest

**Comment by naser-ali** [comment]
Same here. Running latest HA Core on ubuntu 22.04.

This error originated from a custom integration.
Logger: homeassistant.config_entries
Source: custom_components/blueair/__init__.py:50
Integration: BlueAir (documentation, issues)
First occurred: 14:19:38 (3 occurrences)
Last logged: 14:39:35

Error setting up entry BlueAir XXX for blueair
Traceback (most recent call last):
  File "/srv/homeassistant/lib/python3.10/site-packages/homeassistant/config_entries.py", line 387, in async_setup
    result = await component.async_setup_entry(hass, self)
  File "/home/homeassistant/.homeassistant/custom_components/blueair/__init__.py", line 50, in async_setup_entry
    hass.config_entries.async_setup_platforms(entry, PLATFORMS)
AttributeError: 'ConfigEntries' object has no attribute 'async_setup_platforms'

**Comment by RenfoJu1** [comment]
me too; same logs

**Comment by Tokynet** [comment]
@aijayadams any update for this issue?

**Comment by ychanteloup** [comment]
Tried to reinstall: This error originated from a custom integration.

Logger: homeassistant.config_entries
Source: custom_components/Blueair/__init__.py:50 
Integration: Blueair 
First occurred: 22:07:52 (1 occurrences) 
Last logged: 22:07:52

Error setting up entry BlueAir xx@xx.com for blueair
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 387, in async_setup
    result = await component.async_setup_entry(hass, self)
  File "/config/custom_components/Blueair/__init__.py", line 50, in async_setup_entry
    hass.config_entries.async_setup_platforms(entry, PLATFORMS)
AttributeError: 'ConfigEntries' object has no attribute 'async_setup_platforms'

**Comment by whozur** [comment]
yep, definitely busted...

`2023-07-20 13:21:11.760 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry BlueAir xxxx@xxxx.com for blueair
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 390, in async_setup
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/blueair/__init__.py", line 50, in async_setup_entry
    hass.config_entries.async_setup_platforms(entry, PLATFORMS)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^`

**Comment by RenfoJu1** [comment]
Reason is described here: 
https://developers.home-assistant.io/blog/2022/07/08/config_entry_forwards/

**Comment by Komentorivi** [comment]
Same error on Blueair Classic 405, HA 2023.9.1

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 387, in async_setup
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/blueair/__init__.py", line 50, in async_setup_entry
    hass.config_entries.async_setup_platforms(entry, PLATFORMS)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'ConfigEntries' object has no attribute 'async_setup_platforms'
